### ISSUE TITLE
getBalanceOperations

### ISSUE THREAD

**Issue by ariellcannal** [pagarme/pagarme-php-sdk#38]
Estou implementando o controle de operações na minha aplicação, mas tenho enfrentado dificuldades mesmo em requisições bem simples. Alguem já passou por isso e pode me ajudar?

```
            $balanceOperationsController = $client->getBalanceOperationsController();
            
            $status = 'transferred';
            $createdSince = new DateTime(date());
            $createdSince = null;
            $createdUntil = null;
            $recipientId = null;
            
            $operations = $balanceOperationsController->getBalanceOperations(
                $status,
                $createdSince,
                $createdUntil,
                $recipientId
                );
```

e recebo a Exception:
`Error: Object of class stdClass could not be converted to string in /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php:464
Stack trace:
#0 /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php(464): settype('', 'string')
#1 /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php(301): apimatic\jsonmapper\JsonMapper->getMappedValue('', 'string', NULL, NULL, 'PagarmeApiSDKLi...', 'PagarmeApiSDKLi...', false)
#2 /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php(1192): apimatic\jsonmapper\JsonMapper->map(Object(stdClass), Object(PagarmeApiSDKLib\Models\GetMovementObjectTransferResponse), false)
#3 /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php(522): apimatic\jsonmapper\JsonMapper->mapClass(Object(stdClass), '\\PagarmeApiSDKL...', false)
#4 /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php(301): apimatic\jsonmapper\JsonMapper->getMappedValue(Object(stdClass), '\\PagarmeApiSDKL...', NULL, NULL, 'PagarmeApiSDKLi...', 'PagarmeApiSDKLi...', false)
#5 /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php(1421): apimatic\jsonmapper\JsonMapper->map(Object(stdClass), Object(PagarmeApiSDKLib\Models\GetBalanceOperationResponse), false)
#6 /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php(504): apimatic\jsonmapper\JsonMapper->mapArray(Array, Array, '\\PagarmeApiSDKL...', 1, false)
#7 /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php(301): apimatic\jsonmapper\JsonMapper->getMappedValue(Array, 'GetBalanceOpera...', NULL, NULL, 'PagarmeApiSDKLi...', 'PagarmeApiSDKLi...', false)
#8 /home/grupotapa/public_html/grupos/vendor/apimatic/jsonmapper/src/JsonMapper.php(1192): apimatic\jsonmapper\JsonMapper->map(Object(stdClass), Object(PagarmeApiSDKLib\Models\ListBalanceOperationResponse), false)
#9 /home/grupotapa/public_html/grupos/vendor/apimatic/core/src/Utils/JsonHelper.php(71): apimatic\jsonmapper\JsonMapper->mapClass(Object(stdClass), 'PagarmeApiSDKLi...')
#10 /home/grupotapa/public_html/grupos/vendor/apimatic/core/src/Response/Types/ResponseType.php(70): Core\Utils\JsonHelper->mapClass(Object(stdClass), 'PagarmeApiSDKLi...', 0)
#11 /home/grupotapa/public_html/grupos/vendor/apimatic/core/src/Response/ResponseHandler.php(159): Core\Response\Types\ResponseType->getFrom(Object(Core\Response\Context))
#12 /home/grupotapa/public_html/grupos/vendor/apimatic/core/src/ApiCall.php(51): Core\Response\ResponseHandler->getResult(Object(Core\Response\Context))
#13 /home/grupotapa/public_html/grupos/vendor/pagarme/pagarme-php-sdk/src/Controllers/BaseController.php(44): Core\ApiCall->execute()
#14 /home/grupotapa/public_html/grupos/vendor/pagarme/pagarme-php-sdk/src/Controllers/BalanceOperationsController.php(52): PagarmeApiSDKLib\Controllers\BaseController->execute(Object(Core\Request\RequestBuilder), Object(Core\Response\ResponseHandler))
#15 /home/grupotapa/public_html/grupos/application/libraries/Pagarme.php(466): PagarmeApiSDKLib\Controllers\BalanceOperationsController->getBalanceOperations('transferred', NULL, NULL, NULL)
#16 /home/grupotapa/public_html/grupos/application/controllers/Ajax.php(70): Pagarme->get_operations()
#17 {main}`

**Comment by fellipgomes** [comment]
Amigo @ariellcannal conseguiu resolver?

Vc sabe fazer cobranças em cartão de crédito? estou tendo problemas 

Boa rapaziada como estão? 

Amigos, minha aplicação faz chamadas para geração de pix e confirma os pagamentos, desejo realizar cobranças com cartão de crédito, mas sempre que faço um Post passando os dados do cartão e do cliente o antifraude bloqueia a compra e força reembolso ao cliente.

Podem ajudar com isso?

`POST /core/v5/orders HTTP/1.1
Host: api.pagar.me
User-Agent: Minha APII
Authorization: Basic AAAAAAAAAAA
Content-Type: application/json
Content-Length: 1390


{
    "items": [
        {
            "amount": 190,
"code":1,
            "description": "Ação participação",
            "quantity": 1
        }
    ],
    "customer": {
        "name": "Fellip Melo",
        "email": "fellipdxxx@gmail.com",
"type": "individual",
"document": "069256xxxx",
	"phones":
		{
			"home_phone":
			{
				"country_code": "55",
				"number": "9841xxxxx",
				"area_code": "34"
			}
		}
    },
    "payments": [
        {
            "payment_method": "credit_card",
"ip":"168.xxx.149.xxx",
"antifraud_enabled":false,
            "credit_card": {
                "recurrence": false,
                "installments": 1,
                "statement_descriptor": "participacao",
"operation_type":"pre_auth",

                "card": {
                    "number": "55020xxx8546xxxx",
                    "holder_name": "Fellip de Melo",
                    "exp_month": 03,
                    "exp_year": 32,
                    "cvv": "xxx",
                    "billing_address": {
                        "line_1": "Rua xxx arinos 302",
                        "zip_code": "38xxxxxx",
                        "city": "Uberlândia",
                        "state": "MG",
                        "country": "BR"                
                    }
                }
            }
        }
    ]
}`

Resposta da requisição:

`       },
        "antifraud_response": {
          "status": "reproved",
          "score": "very_high",
          "provider_name": "pagarme"
        },`

**Comment by ariellcannal** [comment]
Oi, @fellipgomes !
Eu faço as cobrança de cartão de crédito normalmente utilizando esse SDK. Não faço a chamada POST diretamente utilizo a lib para isso. Nunca tive problemas.

**Comment by ariellcannal** [comment]
Consegui resolver a Exception. Há um erro no SDK, já fiz o Pull Request, veja:
https://github.com/pagarme/pagarme-php-sdk/pull/39/commits/2922663cac523b1a52ea88ce55ecc79850e02747

**Comment by fellipgomes** [comment]
> Oi, @fellipgomes ! Eu faço as cobrança de cartão de crédito normalmente utilizando esse SDK. Não faço a chamada POST diretamente utilizo a lib para isso. Nunca tive problemas.

No caso utilizando a sdk você passa da mesma forma os números do cartão e cvv?

Ou faz algo de pegar o token do cartão no front e leva para o back?
